services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8090:5432"
    networks:
      - postgres
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7.4.3
    restart: always
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "12345"] 
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "12345", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
      postgres:
        driver: bridge
      redis:
        driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: